# Generated by Django 5.1.2 on 2024-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_message',
            field=models.TextField(blank=True, help_text='Custom message to send to all attendees.', null=True),
        ),
    ]
