# Generated by Django 5.1.2 on 2024-11-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0002_event_custom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='custom_message',
        ),
    ]
