# Generated by Django 5.1.2 on 2024-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('university', 'University'), ('highschool', 'High School'), ('sponsor', 'Sponsor'), ('staff', 'Staff')], default='university', max_length=20),
        ),
    ]
