# Generated by Django 5.1.2 on 2024-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_alter_profile_bio_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor_cellphone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='past_participation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_programming_language',
            field=models.CharField(blank=True, help_text='e.g. Python', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('university', 'University'), ('highschool', 'High School'), ('sponsor', 'Sponsor'), ('volunteer', 'volunteer')], default='university', max_length=20),
        ),
    ]
