# Generated by Django 5.1.2 on 2024-10-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcementsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.AddField(
            model_name='announcement',
            name='info',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
