# Generated by Django 5.1.2 on 2024-10-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcementsApp', '0002_remove_announcement_content_remove_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
