# Generated by Django 5.1.2 on 2024-10-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcementsApp', '0003_announcement_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
    ]
