# Generated by Django 5.1.2 on 2024-10-31 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcementsApp', '0004_remove_announcement_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='emailed_users',
            field=models.ManyToManyField(blank=True, related_name='emailed_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
